name: golconda
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - pip
  - numpy
  - scipy
  - matplotlib
  - pandas
  - healpy
  - jupyter
  - notebook
  - ipykernel
  - sphinx
  - sphinx-autodoc-typehints
  - sphinx_rtd_theme
  - scikit-learn
  - matplotlib-base
  - mpmath
  - pyccl
  - jax
  - pyfftw
  - lenspack
  - scikit-image
  - pip:
      - tqdm